# Copyright (c) 2026, Printechs and contributors
# License: MIT. See license.txt

from __future__ import annotations

import re

import frappe
from frappe.utils import cint, sanitize_html

DEFAULT_HELP_CATEGORY = "ERPNext Basics"
HELP_MODULE_AREAS = frozenset(
	{"Support", "WMS", "ERPNext", "Sales", "Purchase", "Stock", "Accounts", "HR", "General"}
)


def _normalize_help_module_area(module_area: str | None) -> str:
	value = (module_area or "ERPNext").strip()
	return value if value in HELP_MODULE_AREAS else "ERPNext"


def ensure_studio_help_category(category_name: str | None = None) -> str:
	name = (category_name or DEFAULT_HELP_CATEGORY).strip()
	if frappe.db.exists("Help Category", name):
		return name
	frappe.get_doc(
		{
			"doctype": "Help Category",
			"category_name": name,
			"module_area": "ERPNext",
			"description": "Generated by PRAI Studio.",
			"sort_order": 60,
			"is_active": 1,
		}
	).insert(ignore_permissions=True)
	return name


def generate_draft_help_articles_from_findings(
	findings: list[dict],
	*,
	help_category: str,
	module_area: str = "ERPNext",
	product_name: str = "Modern POS",
	health_results: list[dict] | None = None,
) -> list[dict]:
	items: list[dict] = []
	seen: set[str] = set()
	category = ensure_studio_help_category(help_category)
	module_area = _normalize_help_module_area(module_area)

	grouped: dict[str, list[dict]] = {}
	for row in findings:
		grouped.setdefault(row.get("finding_type") or "Source", []).append(row)

	for finding_type, rows in grouped.items():
		if finding_type in {"Ignored", "Error"}:
			continue
		title = f"{product_name} — {finding_type} modules guide"
		if title.lower() in seen:
			continue
		seen.add(title.lower())
		lines = [f"<li><strong>{row.get('title')}</strong> — {sanitize_html(row.get('summary') or '')}</li>" for row in rows[:20]]
		content = (
			f"<p>Guide generated from PRAI Studio analysis of {product_name} source code.</p>"
			f"<h3>{finding_type} findings</h3><ul>{''.join(lines)}</ul>"
		)
		items.append(
			{
				"title": title,
				"summary": f"Overview of {finding_type.lower()} modules detected in uploaded source.",
				"keywords": f"{finding_type.lower()}, {product_name.lower()}, source, studio",
				"help_category": category,
				"module_area": module_area,
				"content": content,
				"source_finding": f"{finding_type} group",
			}
		)

	for row in findings:
		if (row.get("finding_type") or "") not in {"Documentation", "Form", "Api"}:
			continue
		title = (row.get("title") or "").strip()
		if not title or title.lower() in seen:
			continue
		detail = sanitize_html(row.get("detail") or row.get("summary") or "")
		if len(detail) < 40:
			continue
		guide_title = f"{product_name} — {title[:100]}"
		if guide_title.lower() in seen:
			continue
		seen.add(guide_title.lower())
		items.append(
			{
				"title": guide_title,
				"summary": sanitize_html(row.get("summary") or "")[:240],
				"keywords": f"{product_name.lower()}, {_path_basename(row)}, documentation",
				"help_category": category,
				"module_area": module_area,
				"content": f"<p>{detail}</p>",
				"source_finding": title,
			}
		)

	for health in health_results or []:
		if health.get("result_status") not in {"Warning", "Fail"}:
			continue
		if not cint(health.get("include_in_generation")):
			continue
		title = f"{product_name} health check — {health.get('rule_key')}"
		if title.lower() in seen:
			continue
		seen.add(title.lower())
		detail = sanitize_html(health.get("detail") or health.get("summary") or "")
		items.append(
			{
				"title": title,
				"summary": sanitize_html(health.get("summary") or "")[:240],
				"keywords": f"health check, {health.get('rule_key')}, promotion, modern pos",
				"help_category": category,
				"module_area": "ERPNext",
				"content": f"<p>{sanitize_html(health.get('summary') or '')}</p><pre>{detail}</pre>",
				"source_finding": health.get("rule_key") or "",
			}
		)
	return items[:25]


def draft_help_lines_from_items(items: list[dict]) -> list[dict]:
	lines: list[dict] = []
	for item in items:
		lines.append(
			{
				"include": 1,
				"review_status": "Draft",
				"title": item.get("title"),
				"summary": item.get("summary") or "",
				"keywords": item.get("keywords") or "",
				"help_category": item.get("help_category") or ensure_studio_help_category(None),
				"module_area": _normalize_help_module_area(item.get("module_area") or "ERPNext"),
				"content": item.get("content") or "",
				"source_finding": item.get("source_finding") or "",
				"help_article": "",
			}
		)
	return lines


def upsert_help_articles(items: list[dict], *, update_existing: bool = True) -> dict:
	created = 0
	updated = 0
	skipped = 0
	for item in items:
		title = (item.get("title") or "").strip()
		category = item.get("help_category") or ensure_studio_help_category(None)
		if not title or not (item.get("content") or "").strip():
			skipped += 1
			continue
		existing = frappe.db.get_value("Help Article", {"title": title, "category": category}, "name")
		payload = {
			"summary": item.get("summary") or "",
			"keywords": item.get("keywords") or "",
			"content": item.get("content") or "",
			"module_area": _normalize_help_module_area(item.get("module_area") or "ERPNext"),
			"status": "Published",
			"show_in_portal": 1,
			"show_in_desk": 1,
			"allow_customer_view": 1,
		}
		if existing:
			if not update_existing:
				skipped += 1
				continue
			doc = frappe.get_doc("Help Article", existing)
			for key, value in payload.items():
				doc.set(key, value)
			doc.save(ignore_permissions=True)
			updated += 1
			continue
		doc = frappe.get_doc({"doctype": "Help Article", "title": title, "category": category, **payload})
		doc.insert(ignore_permissions=True)
		created += 1
	return {"created": created, "updated": updated, "skipped": skipped}


def _path_basename(row: dict) -> str:
	path = (row.get("file_path") or "").split("/")[-1]
	return re.sub(r"[^\w.]+", " ", path).strip()
